defaults:
  - _self_

model:
  name: regression

  hr_mean_conditioning: false

  model_args:

    img_resolution: [32, 32]

    in_channels: 2
    out_channels: 1

    model_channels: 16

    channel_mult: [1, 2, 2]

    attn_resolutions: [16]

    num_blocks: 1

    dropout: 0.1

    embedding_type: positional

    channel_mult_noise: 1

    encoder_type: standard
    decoder_type: standard

    resample_filter: [1, 1]

    N_grid_channels: 0

dataset:
  type: /home/vsantos/rionowcast/repositories/physicsnemo/examples/weather/corrdiff/datasets/zarr_dataset.py::ZarrCorrDiffDataset
    #type: ~/rionowcast/repositories/physicsnemo/examples/weather/corrdiff/datasets/zarr_dataset.py::ZarrCorrDiffDataset

  path: /home/vsantos/rionowcast/datasets/corrdiff/train.zarr

  normalization_path: /home/vsantos/rionowcast/datasets/corrdiff/normalization.npz

  train_indices: home/vsantos/rionowcast/datasets/corrdiff/train_idx.npy

  valid_indices: home/vsantos/rionowcast/datasets/corrdiff/valid_idx.npy

training:

  hp:

    total_batch_size: 8

    batch_size_per_gpu: 1

    lr: 1e-4

    training_duration: 1000

    lr_rampup: 100

    lr_decay: 0.999

    lr_decay_rate: 500

    grad_clip_threshold: 1.0

  perf:

    fp_optimizations: none

    dataloader_workers: 2

    torch_compile: false

    songunet_checkpoint_level: 0

    cudnn_benchmark: false

    find_unused_parameters: false

    persistent_workers: true

    pin_memory: true

    prefetch_factor: 4

  io:

    checkpoint_dir: checkpoints/regression

    save_checkpoint_freq: 100

    validation_freq: 50

    validation_steps: 2

    print_progress_freq: 10

wandb:

  mode: offline

  watch_model: false

  results_dir: outputs
