defaults:
  - _self_

model:
  name: diffusion

  hr_mean_conditioning: true

  regression_checkpoint: checkpoints/regression/latest.pt

  model_args:

    img_resolution: [32, 32]

    in_channels: 1
    out_channels: 1

    model_channels: 128

    channel_mult: [1, 2, 2, 4]

    attn_resolutions: [16]

    num_blocks: 2

    dropout: 0.1

    embedding_type: positional

    channel_mult_noise: 2

    encoder_type: standard
    decoder_type: standard

dataset:

  type: zarr

  path: /home/sangonvi/Cefet/datasets/corrdiff/train.zarr

  normalization_path: /home/sangonvi/Cefet/datasets/corrdiff/normalization.npz

  train_indices: /home/sangonvi/Cefet/datasets/corrdiff/train_idx.npy

  valid_indices: /home/sangonvi/Cefet/datasets/corrdiff/valid_idx.npy

training:

  hp:

    total_batch_size: 16

    batch_size_per_gpu: 2

    lr: 2e-4

    training_duration: 600000

    lr_rampup: 10000

  perf:

    fp_optimizations: amp-bf16

    dataloader_workers: 8

  io:

    checkpoint_dir: checkpoints/diffusion

    save_checkpoint_freq: 10000

    validation_freq: 5000

wandb:

  mode: offline