defaults:
  - _self_

model:

  name: diffusion

  hr_mean_conditioning: true

  model_args:

    img_resolution: [32, 32]

    in_channels: 1
    out_channels: 1

    model_channels: 64

    channel_mult: [1, 2, 2, 4]

    attn_resolutions: [16]

    num_blocks: 2

    dropout: 0.10

    embedding_type: positional

    channel_mult_noise: 2

    encoder_type: standard
    decoder_type: standard
dataset:
  type: /home/vsantos/rionowcast/repositories/physicsnemo/examples/weather/corrdiff/datasets/zarr_dataset.py::ZarrCorrDiffDataset

  path: /home/vsantos/rionowcast/datasets/corrdiff/train.zarr

  normalization_path: /home/vsantos/rionowcast/datasets/corrdiff/normalization.npz

  train_indices: /home/vsantos/rionowcast/datasets/corrdiff/train_index.npy

  valid_indices: /home/vsantos/rionowcast/datasets/corrdiff/valid_index.npy

training:

  hp:

    total_batch_size: 16

    batch_size_per_gpu: 2

    lr: 2e-4

    lr_rampup: 10000

    lr_decay: 1.0
    lr_decay_rate: 1000000

    grad_clip_threshold: 1.0

    training_duration: 100000

  perf:

    fp_optimizations: fp32

    dataloader_workers: 8

    songunet_checkpoint_level: 0

    torch_compile: false

    use_apex_gn: false

    profile_mode: false

  io:

    regression_checkpoint_path: checkpoints/regression/checkpoints_regression/CorrDiffRegressionUNet.0.100000.mdlus

    checkpoint_dir: checkpoints/diffusion

    print_progress_freq: 100

    validation_freq: 5000

    validation_steps: 10

    save_checkpoint_freq: 10000

    save_n_recent_checkpoints: 5

wandb:

  mode: offline

  watch_model: false

  results_dir: wandb